name: Codecov Report
on: pull_request

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    - name: Upload coverage reports to Codecov
    uses: actions/checkout@v2
    uses: codecov/codecov-action@v3
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    with:
      files: ./_coverage/coverage.xml
      env_vars: OS,PYTHON,TEST_DATABASE_URI
      fail_ci_if_error: true